# Transform MCMC posteriors from matrix to data.frame
# df is a data.frame generated by get_df_varname
# mcmc_nimble is a list of matrix. Each matrix are mcmc posteriors for a chain
# with different variables in column and iterations in line
# burnin is the number of iterations that should be dropped (may be dropped
# afterwards as well)

get_mcmc <- 
  function(df, mcmc_nimble, burnin){
    listvar <- unique(df$fullname)
    listdf <- list()
    # browser()
    for(thischain in 1:length(mcmc_nimble)){
      # message("load chain ", thischain)
      mcmc_tmp <- mcmc_nimble[[thischain]][,listvar]
      niter <- nrow(mcmc_tmp)
      # message('start for')
      listdf[[thischain]] <- data.frame(fullname = rep(listvar, each = (niter-burnin)),
                                        value = c(mcmc_tmp[(burnin+1):niter,]),
                                        chain = thischain,
                                        iter = rep((burnin+1):niter,length(listvar)))
      
    }
    totcluster <- do.call('rbind', listdf)
    returndf <- dplyr::left_join(totcluster, df, by = "fullname")
    return(returndf)
  }