---
title: "Stock-Recruitment for model `r model_name`"
author: "Remi Patin"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    css: toc.css
    toc: true
    toc_depth: 5
    number_sections: true
---

```{r global_options,include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE,fig.width=8,fig.height=4,bg="transparent")
```

# Stock Recruitment Relationship

```{r}

subdfN1 <- filter(dfmed, name %in% c("N1")) %>% 
  mutate(year = 1993+dim1) %>% 
  select(N1 = median, N1_q5 = q5, N1_q95 = q95,  year )
subdfN2 <- filter(dfmed, name %in% c("N2"))%>% 
  mutate(year = 1993+dim1) %>% 
  select(N2 = median, N2_q5 = q5, N2_q95 = q95,  year)
subdfN2mean <- filter(dfmed, name %in% c("logN2_mean"))%>% 
  mutate(year = 1993+dim1) %>% 
  select(logN2 = median, logN2_q5 = q5, logN2_q95 = q95,  year)
subdf <- inner_join(subdfN1,
                    subdfN2, 
                    by = "year") %>% 
  inner_join(.,subdfN2mean, by = "year") %>% 
  filter(year > 1997)

this_alpha <- (filter(dfmed, name == "alpha"))$median
this_k <- (filter(dfmed, name == "k"))$median
this_sd_logN2 <- (filter(dfmed, name == "logN2_sd"))$median

N1_test <- seq(0, max(subdf$N1), length.out = 100)
lapply(N1_test, function(N1){
  meanN2 <- log(N1/(1/this_alpha + N1/this_k))
  x <- rlnorm(n = 100000, meanlog = meanN2-0.5*this_sd_logN2^2, sdlog = this_sd_logN2)
  return(data.frame(N1 = N1,
                    N2 = median(x),
                    N2q5 = quantile(x, 0.05),
                    N2q95 = quantile(x, 0.95)))
}) %>% data.table::rbindlist() -> dfsimul

ggplot(subdf)+
  geom_ribbon(data = dfsimul, aes(x= N1, ymin = N2q5, ymax = N2q95), alpha = 0.2, fill = "brown")+
  geom_line(data = dfsimul, aes(x= N1, y = N2), color = "brown")+
  geom_point(aes(x = N1, y = N2))+
  # geom_line(aes(x= N1, y = exp(logN2-0.5*this_sd_logN2^2)))+
  # geom_errorbar(aes(x = N1, ymin = N2_q5,ymax = N2_q95))+
  # geom_errorbarh(aes(y = N2, xmin = N1_q5,xmax = N1_q95))+
  xlab("Egg deposition")+
  ylab("N(0+)")
```

# residuals

```{r}

ggplot(subdf)+
  geom_histogram(aes(x = log(N2)-logN2+0.5*this_sd_logN2^2))+
  xlab("Residuals")
```

# alpha & k

```{r, results = 'asis',fig.width=8,fig.height=4}
list_var <- c("alpha",
              "k")

subdf_med <- filter(dfmed, name %in% list_var)

subdf <- filter(dfres,
                name %in% list_var,
                iter > burnin_output)
ggplot(subdf)+
  geom_density(aes(x = value))+
  geom_vline(data = subdf_med,
             aes(xintercept = q5), linetype = 2)+
  geom_vline(data = subdf_med,
             aes(xintercept = q95), linetype = 2)+
  # geom_label(data = filter(dfmed, name %in% list_var),
  # aes(x = (3*max+min)/4, y = 1, label = glue("median = {round(median, digits = 2)}")))+
  facet_wrap(~name, scales = 'free')+
  scale_x_log10(NULL)-> g
gridExtra::grid.arrange(g)

```
