---
title: "Smolt sex ratio for model `r model_name`"
author: "Remi Patin"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    css: toc.css
    toc: true
    toc_depth: 5
    number_sections: true
---

```{r global_options,include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE,fig.width=8,fig.height=4,bg="transparent")
```

# Smolt Sex Ratio

```{r}
subdf <-
  dfmed %>% 
  filter(name %in% c("prop3f")) %>% 
  mutate(year = dim1+1993) %>% 
  filter(year >= 1996) 

ggplot(subdf)+
  geom_ribbon(aes(x = year, ymin = q5, ymax = q95), alpha = 0.2)+
  geom_line(aes(x = year, y = median))+
  coord_cartesian(ylim = c(0,1))+
  xlab(NULL)+
  ylab("Prop. female in smolt")
```

# Smolt Freshwater Age

```{r}
subdf <-
  dfmed %>% 
  filter(name %in% c("p_smolt_cohort")) %>% 
  mutate(year = dim1+1993,
         FW = dim2) %>% 
  filter(year >= 1994,
         FW == 1) 

ggplot(subdf)+
  geom_ribbon(aes(x = year, ymin = q5, ymax = q95), alpha = 0.2)+
  geom_line(aes(x = year, y = median))+
  coord_cartesian(ylim = c(0,1))+
  scale_x_continuous(NULL, breaks = scales::pretty_breaks(n  = 5))+
  ylab("Prop. of parr cohort\nmigrating as smolt 1")
```
